### ISSUE TITLE
Bug found.

### ISSUE THREAD

**Issue by dalwadi2** [AgarwalPragy/GATE2016_MarksEvaluator#2]
in some branch's or in some response there are error in fetching result.
like , some questions not found in response URL .
fix them.
and nice work ...

**Comment by AgarwalPragy** [comment]
Sorry, the application is only for Computer Science. A message stating the same has been added, and will be pushed to the server soon.

**Comment by dalwadi2** [comment]
Okay No problem ..
Good luck .
